import type { Metadata } from "next";
import ThemeRegistry from "./theme/ThemeRegistry";
import "./globals.css";
import ClientLayout from "./authclientlayout";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from "next-intl/server";
import { LanguageProvider } from "./contexts/LanguageContext";
export const metadata: Metadata = {
  title: "CTO Project",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const messages = await getMessages();
  const locale = await getLocale();
  // const dir = locale === "ar" ? "rtl" : "ltr";
  return (
    <html lang={locale} >
           {/* <html lang="en"> */}
      <body suppressHydrationWarning={true}>
        <LanguageProvider>
        <ThemeRegistry>
          <ClientLayout>
            <NextIntlClientProvider messages={messages} locale={locale}>
          {children}
          </NextIntlClientProvider>
          </ClientLayout>
          </ThemeRegistry>
          </LanguageProvider>
      </body>
    </html>
  );
}
